export { default as Home } from './Home'
export { default as CommentsPage } from './CommentsPage'
export { default as CreatePost } from './CreatePost'
export { default as Login } from './Login'
export { default as SignUp } from './SignUp'
export { default as Page404 } from './Page404'
